spring.application.name=bank

# ===============================
# SQLite Database Configuration
# ===============================
spring.datasource.url=jdbc:sqlite:egabank.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# Désactiver H2 Console
spring.h2.console.enabled=false

# Désactiver docker compose
spring.docker.compose.enabled=false

# ===============================
# JWT Configuration
# ===============================
jwt.secret=YmFua2VnYXNlY3JldGtleWZvcmp3dGF1dGhlbnRpY2F0aW9uMjAyNg==
jwt.expiration=86400000
